# Site Settings
title:               "Nitin J. Sanket"
tagline:             
description:         
baseurl:             # /
url: 			           
github:
  repo:              "https://github.com/NitinJSanket/nitinjsanket.github.io"
author: 
  name:              "Nitin J. Sanket"
  email:             
  twitter:           
  instagram:         "firenitin"
  github:            "nitinjsanket"
  facebook:          "nitin.jsanket"
  linkedin:          "nitinjsanket"
  scholar:           "ugyWSWwAAAAJ"
  500px:             "nitinjsanket"
  googleplus:        "109668763227339118292"
paginate:            15
paginate_path:       "/blog/page:num/"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           pretty
plugins:             [jekyll-paginate]
mathjax: 	     true

# Collections
collections:
  - research
  - teaching
  - projects
  - service