# Site Settings
title:               "Nitin J. Sanket"
tagline:             "Ph.D. Candidate in Computer Science at the University of Maryland, College Park"
description:         "Lee Clement is a Ph.D. Candidate in Robotics at the University of Toronto, supervised by Prof. Jonathan Kelly. His research interests include mobile robotics, state estimation, computer vision and machine learning."
baseurl:             # /
url: 			           # http://leeclem.net
github:
  repo:              "https://github.com/NitinJSanket/nitinjsanket.github.io"
author:
  name:              "Nitin J. Sanket"
  email:             "nitin@cs.umd.edu"
  twitter:           
  instagram:         "firenitin"
  github:            "nitinjsanket"
  facebook:          
  linkedin:          "nitinjsanket"
  scholar:           "ugyWSWwAAAAJ"
paginate:            15
paginate_path:       "/blog/page:num/"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           pretty
plugins:             [jekyll-paginate]

# Collections
collections:
  - research
  - teaching
  - service