# Site Settings
title:               "Nitin J. Sanket"
tagline:             
description:         
baseurl:             # /
url: 			           
github:
  repo:              "https://github.com/NitinJSanket/nitinjsanket.github.io"
author: 
  name:              "Nitin J. Sanket"
  email:             "nitin@cs.umd.edu"
  twitter:           
  instagram:         "firenitin"
  github:            "nitinjsanket"
  facebook:          
  linkedin:          "nitinjsanket"
  scholar:           "ugyWSWwAAAAJ"
paginate:            15
paginate_path:       "/blog/page:num/"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           pretty
plugins:             [jekyll-paginate]

# Collections
collections:
  - research
  - teaching
  - service